VirginLifecareWeb/VirginLifecareWeb/Controllers/PartialViewController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Vhm.Web.BL;
using Vhm.Web.Models.InputModels;
using System.Globalization;

namespace VirginLifecareWeb.Controllers
{
    public class PartialViewController : ControllerBase
    {
        //[ChildActionOnly]
        //public ActionResult Invite(long memberId)
        //{
        //    var viewModel = PartialViewsBL.GetInviteFriendsGroupsVM("", new PagingIM());

        //    return View("Invite", viewModel);
        //}

        public ActionResult PopulateInvitedFriendsList(List<long> memberIds, List<long> groupIds, List<long> existingList)
        {
            var memberId = VhmSession.MemberID;
            var sessionId = VhmSession.SessionID;
            var lst = PartialViewsBL.GetNewInviteList(sessionId, memberId, memberIds, groupIds, existingList);
            
            return Json(lst.Select(m => new { m.Member.MemberId, m.Member.FirstName, m.Member.LastName}));
        }

        [HttpPost]
        public string UploadCSVFile(HttpPostedFileBase fileBase)
        {
            var csvStreamReader = new StreamReader(fileBase.InputStream);
            var mIds = PartialViewsBL.GetMemeberIdFromCSV(VhmSession.SessionID, csvStreamReader);
            var serializer = new JavaScriptSerializer();

            return serializer.Serialize(mIds);
        }

        public ActionResult GetMoreFriends(PagingIM paging)
        {
            var sessionId = VhmSession.SessionID;
            paging.MemberId = VhmSession.MemberID;
            var lst = PartialViewsBL.GetMoreFriends(sessionId, paging);
            
            return Json(lst.Select(m => new { Id = m.Member.MemberId, m.Member.FirstName, m.Member.LastName, m.Member.ImageUrl, Sponsor = m.Member.Sponsors.Split(',').First() }));
        }

        public ActionResult GetMoreGroups(PagingIM paging)
        {
            var sessionId = VhmSession.SessionID;
            paging.MemberId = VhmSession.MemberID;
            var lst = PartialViewsBL.GetMoreGroups(sessionId, paging, false);

            return Json(lst.Select(g => new { g.Group.Id, g.Group.Name, g.Group.Category, g.Group.ProfilePicturePath }));
        }

        public string GetMemberImage(long id)
        {
		    if (!String.IsNullOrEmpty(Request.Headers["If-Modified-Since"]))
		    {
			    CultureInfo provider = CultureInfo.InvariantCulture;
			    var lastMod = DateTime.ParseExact(Request.Headers["If-Modified-Since"], "r", provider).ToLocalTime();
			    if (DateTime.Now.CompareTo(lastMod) < 30)
			    {
				    Response.StatusCode = 304;
				    Response.StatusDescription = "Not Modified";
				    //return Content(String.Empty);
			    }
		    }
            var imagePath = PartialViewsBL.GetMemberImagePath(id);
            return imagePath;// base.File( imagePath, "image/jpeg" );
        }

        //this method is used by some of the front end functionality, so we'll return a string with the image path
        public ActionResult GetGroupImage(long id)
        {

	        if (!String.IsNullOrEmpty(Request.Headers["If-Modified-Since"]))
	        {
		        CultureInfo provider = CultureInfo.InvariantCulture;
		        var lastMod = DateTime.ParseExact(Request.Headers["If-Modified-Since"], "r", provider).ToLocalTime();
		        if (DateTime.Now.CompareTo(lastMod) < 30)
		        {
			        Response.StatusCode = 304;
			        Response.StatusDescription = "Not Modified";
			        return Content(String.Empty);
		        }
	        }

            var defaultImagePath = Server.MapPath("~/Content/images/social/img-no-group.png");
            var imageData = PartialViewsBL.GetGroupImage(id, defaultImagePath);
	        var stream = new MemoryStream(imageData);
	        Response.Cache.SetCacheability(HttpCacheability.Public);
	        Response.Cache.SetLastModified(DateTime.Now);
	        return File(stream, "image/jpeg");
        }

        //this method is used by some of the front end functionality, so we'll return a string with the image path
        public ActionResult GetGroupImagePath(long id)
        {

	        if (!String.IsNullOrEmpty(Request.Headers["If-Modified-Since"]))
	        {
		        CultureInfo provider = CultureInfo.InvariantCulture;
		        var lastMod = DateTime.ParseExact(Request.Headers["If-Modified-Since"], "r", provider).ToLocalTime();
		        if (DateTime.Now.CompareTo(lastMod) < 30)
		        {
			        Response.StatusCode = 304;
			        Response.StatusDescription = "Not Modified";
			        return Content(String.Empty);
		        }
	        }
            var imageData = PartialViewsBL.GetGroupImagePath(id);
            return File(imageData, "image/jpeg");
        }

        /// <summary>
        /// Get the profile with the appropriate permissions for the current user.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult GetMemberProfile(long id)
        {
            var sessionId = VhmSession.SessionID;
            var currentMemberId = VhmSession.MemberID;
            var memberVm = SocialBL.GetMemberProfile(sessionId, id, currentMemberId, false);
            memberVm.Culture = new CultureInfo(VhmSession.Culture);

            return View("Member/MemberProfile", memberVm);
        }

        public ActionResult GetMembersByEmailsOrIdentityNumbers(IEnumerable<string> emailsAndidentityNumbers)
        {
            var members = SocialBL.GetMembersByEmailsOrIdentityNumbers(VhmSession.SessionID, emailsAndidentityNumbers);
            var mIds = members.Select(m => m.Member.MemberId).ToList();

            return Json(mIds);
        }
    }
}

VirginLifecareWeb/VirginLifecareWeb/Controllers/SocialController.cs
using System.Collections.Generic;
using System;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using Vhm.Providers;
using Vhm.Web.BL;
using Vhm.Web.Common;
using Vhm.Web.Models.Enums;
using Vhm.Web.Models.InputModels;
using Vhm.Web.Models.RepositoryModels;
using Vhm.Web.Models.ViewModels.Shared;
using Vhm.Web.Models.ViewModels.Social;
using VirginLifecareWeb.Controllers.ActionResults;
using Member = Vhm.Web.Models.RepositoryModels.Member;

namespace VirginLifecareWeb.Controllers
{
    public class SocialController : ControllerBase
    {

        private const string DEFAULT_CULTURE = "en-US";

        #region Localization


        #endregion Localiaztion

        public ActionResult MyGroups()
        {
            var sessionId = VhmSession.SessionID;
            var memberId = VhmSession.MemberID;
            
            var content = MemberBL.GetContentLabels<MyGroupsContent>(PageNames.MyGroups, LanguageId);
            
            var contentSocial = MemberBL.GetContentLabels<SocialChallengePromotionLabelsContent>(PageNames.SocialChallengePromotionLabels, LanguageId);

            var pageTitle = new PageTitle(true, ContentHeader[HeaderContent.MyGroups]);

            #region set up paging info for paged data
            var pagForMyGroups = new PagingIM { Count = 24, MemberId = memberId, PageNumber = 0 };
            //get 4 so we can render "See More..." 
            var pagForSuggestedGrps = new PagingIM { Count = 4, MemberId = memberId, PageNumber = 0 };
            #endregion

            var modelGroup = new MyGroupsModel();


            var getModelGroup = SocialBL.GetMyGroupsObjects(sessionId, VhmSession.MemberID, pagForMyGroups, pagForSuggestedGrps, false);

            if (getModelGroup != null)
            {


                modelGroup = getModelGroup;
                modelGroup.PageT = pageTitle;
                modelGroup.Content = content;
                modelGroup.ContentSocial = contentSocial;
                #region decode groups names and descriptions
                //this is needed because the one used in Vhm.Web.DataServices\Repositories\SocialRepository seems not to be enough. looks like encoded html still manages to pass through.
                if (modelGroup.PagedGroups.Groups != null && modelGroup.PagedGroups.Groups.Count > 0)
                {
                    foreach (var group in modelGroup.PagedGroups.Groups)
                    {
                        group.Group.Name = DecodeHtml(group.Group.Name);
                        group.Group.Description = DecodeHtml(group.Group.Description);
                        group.Group.Category = DecodeHtml(group.Group.Category);
                    }
                }
                if (modelGroup.SuggestedGroups != null && modelGroup.SuggestedGroups.Count > 0)
                {
                    foreach (var suggestedGroup in modelGroup.SuggestedGroups)
                    {
                        suggestedGroup.Group.Name = DecodeHtml(suggestedGroup.Group.Name);
                        suggestedGroup.Group.Description = DecodeHtml(suggestedGroup.Group.Description);
                        suggestedGroup.Group.Category = DecodeHtml(suggestedGroup.Group.Category);
                    }
                }
                #endregion

                #region get and populate group names suggestions for search group by name
                //get all the group names member is part of, and convert to json - used for suggestions when users starts typing data in search boxes, so they can search by group names
                var listOfGroupNames = SocialBL.GetMemberGroupNames(sessionId, memberId);
                if (listOfGroupNames != null && listOfGroupNames.Count > 0)
                {
                    for (int i = 0; i < listOfGroupNames.Count; i++)
                    {
                        listOfGroupNames[i] = DecodeHtml(listOfGroupNames[i]);
                    }
                    modelGroup.JsonMemberGroupsNames = JsonConvert.SerializeObject(listOfGroupNames);
                }
                else
                {
                    modelGroup.JsonMemberGroupsNames = string.Empty;
                }
                #endregion

                #region get and populate Member friend names suggestions for search group by administrator name
                //get all the group names member is part of, and convert to json - used for suggestions when users starts typing data in search boxes, so they can search by group admins
                var listOfFriendNames = new List<string>();

                // For members with too many friends, this may fail
                try
                {
                    var friendCount = SocialBL.GetMemberFriendCount( memberId );
                    if (friendCount < ApplicationSettings.FriendCountThreshold)
                    {
                        listOfFriendNames = SocialBL.GetMemberFriendNames( sessionId, memberId );
                    }
                }
                catch ( Exception ex )
                {
                    VirginLifecare.Exception.ExceptionHandler.ProcessException(ex);
                }

                if (listOfFriendNames != null && listOfFriendNames.Count > 0)
                {
                    for (int i = 0; i < listOfFriendNames.Count; i++)
                    {
                        listOfFriendNames[i] = DecodeHtml(listOfFriendNames[i]);
                    }
                    modelGroup.JsonMemberFriendsNames = JsonConvert.SerializeObject(listOfFriendNames);
                }
                else
                {
                    modelGroup.JsonMemberFriendsNames = string.Empty;
                }
                #endregion

                var selectedColorTheme = GetSelectedTheme();
                modelGroup.ThemeCode = selectedColorTheme;
            }
            return View(modelGroup);
        }

        public ActionResult _GetPagedGroups(int count, int pageNumber)
        {
            try
            {
                var pagedGroups = new PagedGroupsVM();
                string sessionId = VhmSession.SessionID;
                long memberId = VhmSession.MemberID;

                var pagForMyGroups = new PagingIM { Count = count, MemberId = memberId, PageNumber = pageNumber };

                var getPagedGroups = SocialBL.GetMyGroupsPaged(sessionId, pagForMyGroups, false);
                if (getPagedGroups != null)
                {
                    pagedGroups = getPagedGroups;
                    if (pagedGroups.Groups.Count > 0)
                    {
                        foreach (var groupVm in pagedGroups.Groups)
                        {
                            groupVm.Group.Name = DecodeHtml(groupVm.Group.Name);
                            groupVm.Group.Description = DecodeHtml(groupVm.Group.Description);
                            groupVm.Group.Category = DecodeHtml(groupVm.Group.Category);
                        }
                    }
                }
                return PartialView("_BuildPagedGroups", pagedGroups);
            }
            catch (Exception ex)
            {
                VirginLifecare.Exception.ExceptionHandler.ProcessException(ex);
                return new JsonNetResult { Data = "Service Error" };
            }
        }

        public ActionResult _GetMoreSuggestedGroups(int pageNumber, int groupsPerPage)
        {
            try
            {
                var sessionId = VhmSession.SessionID;
                var paging = new PagingIM
                    {
                    Count = groupsPerPage,
                    MemberId = VhmSession.MemberID,
                    PageNumber = pageNumber
                };

                var pagedGroupsVm = new PagedGroupsVM();
                var getPagedGroups = SocialBL.GetListOfSuggestedGroups(sessionId, paging, false);
                if (getPagedGroups != null)
                {
                    pagedGroupsVm = getPagedGroups;
                    if (pagedGroupsVm.Groups.Count > 0)
                    {
                        #region decode groups names and descriptions
                        foreach (var group in pagedGroupsVm.Groups)
                        {
                            group.Group.Name = DecodeHtml(group.Group.Name);
                            group.Group.Description = DecodeHtml(group.Group.Description);
                            group.Group.Category = DecodeHtml(group.Group.Category);
                        }
                        #endregion
                    }
                }
                return new JsonNetResult { Data = pagedGroupsVm };
            }
            catch (Exception ex)
            {
                VirginLifecare.Exception.ExceptionHandler.ProcessException(ex);
                return new JsonNetResult { Data = "Service Error" };
            }
        }

        public ActionResult _PublicGroupProfile(string group)
        {
            try
            {
                var grpDetails = JsonConvert.DeserializeObject<GroupVM>(group);
                return View(grpDetails);
            }
            catch (Exception ex)
            {
                VirginLifecare.Exception.ExceptionHandler.ProcessException(ex);
                return new JsonNetResult { Data = "Service Error" };
            }
        }
        //to be used for Suggested groups and pending groups - we know member is not part of the group
        public ActionResult _GetPublicGroupProfileFromID(long groupId)
        {
            try
            {
                if (groupId > 0)
                {
                    const int MAX_GROUP_MEMBERS_TO_DISPLAY = 8;
                    var group = SocialBL.GetGroupVMDetails(VhmSession.SessionID, groupId, VhmSession.MemberID, MAX_GROUP_MEMBERS_TO_DISPLAY, false);

VirginLifecareWeb/VirginLifecareWeb/Views/Social/CreateEditGroup.cshtml
@using Vhm.Web.Common
@using Vhm.Web.Models.ViewModels.Shared
@using Vhm.Web.Models.ViewModels.Social
@model Vhm.Web.Models.ViewModels.Social.CreateEditGroupVM
@{
    string action;
    string title;
    if (Model.Mode == "Edit")
    {
        title = Model.ContentCreateGroup[CreateGroupContent.EditGroup];
        action = "UpdateGroup";
    }
    else
    {
        title = Model.ContentCreateGroup[CreateGroupContent.CreateGroup];
        action = "AddGroup";
    }
}
@{
    ViewBag.Title = "CreateEditGroup";
    Layout = "~/Views/Shared/MasterNoCol.cshtml";
    ViewData["pageTitle"] = new PageTitle(Model.PageTitle.ShowPageTitle, title);
    var resourceVersion = ApplicationSettings.CachedResourceVersion;
}
@section Styles
{
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/Style/Invitation.css?v=" + resourceVersion)" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/Style/SocialStyles/SocialStyles.css?v=" + resourceVersion)" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/Style/Shared/PopUp.css?v=" + resourceVersion)" />
}
@section Script
{
    <script type="text/javascript" src="@Url.Content("~/Scripts/Invitation.js?v=" + resourceVersion)"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/VHM/Social/Social.js?v=" + resourceVersion)"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/VHM/Social/CreateEditGroup.js?v=" + resourceVersion)"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/JQuery/tablesorter.js?v=" + resourceVersion)"></script>
    @if (Model.Mode == "Create_1")
    {
        <script type="text/javascript">
            $(function () {
                VHM.SocialGroups.CreateGroupRewardTrigger();
            });
        </script>
    }
}
<div class="span9">
    <input id="hidGroupName" type="hidden" name="Name" value="@Model.GroupVM.Group.Name"/>
    @using (Html.BeginForm(action, "Social", FormMethod.Post, new { @encType = "multipart/form-data" }))
    {
        <input type="hidden" id="groupId" name="Id" value="@Model.GroupVM.Group.Id"/>
        <input type="hidden" id="mode" name="PageMode" value="@Model.Mode"/>
        <input type="hidden" id="hdnLocalization_TextIsAvailable" value="@Model.ContentCreateGroup[CreateGroupContent.TextIsAvailable]"/>
        <input type="hidden" id="hdnLocalization_TextIsAlreadyCreated" value="@Model.ContentCreateGroup[CreateGroupContent.TextIsAlreadyCreated]"/>
        <input type="hidden" id="hdnLocalization_MoreThan3" value="@Model.ContentCreateGroup[CreateGroupContent.NameShouldBeMoreThan3Characters]"/>
        <input type="hidden" id="hdnLocalization_NameIsRequired" value="@Model.ContentCreateGroup[CreateGroupContent.NameIsRequired]"/>
        <input type="hidden" id="hdnLocalization_CategoryIsRequired" value="@Model.ContentCreateGroup[CreateGroupContent.CategoryIsRequired]"/>
        <input type="hidden" id="hdnLocalization_DescriptionIsRequired" value="@Model.ContentCreateGroup[CreateGroupContent.DescriptionIsRequired]"/>
        <input type="hidden" id="hdnLocalization_SomethingWentWrongTryAgain" value="@Model.ContentError[ErrorMessagesContent.SomethingWentWrongPleaseTryAgainLater]"/>
        <input type="hidden" id="hdnLocalization_SomethingWentWrong" value="@Model.ContentError[ErrorMessagesContent.SomethingWentWrong]"/>
        <input type="hidden" id="hdnLocalization_SorrySomethingWentWrong" value="@Model.ContentError[ErrorMessagesContent.SorrySomethingWentWrongWhil_ryAgainLater]"/>
        <input type="hidden" id="hdnLocalization_YouAreAdministrator" value="@Model.ContentGroupCreated[CGYourGroupHasBeenCreatedContent.YouAreAdministratorForThisGroup_toDeleteThisGroup]"/>
        <input type="hidden" id="hdnLocalization_MissingInformation" value="@Model.ContentError[ErrorMessagesContent.MissingInformation]"/>
    

        if (Model.Mode != "Create_1")
        {
        <div class="socCreateGroup divTable">
            <div class="divRow">
                <div class="divCell">
                    <h5>
                        @Model.ContentCreateGroup[CreateGroupContent.GroupName]:</h5>
                </div>
                <div class="divCellRight">
                    <input id="txtGroupName" type="text" name="Name" value="@Model.GroupVM.Group.Name" maxlength="100" />
                    <div id="divGroupAvailability">
                    </div>
                </div>
            </div>
            <div class="divRow">
                <div class="divCell">
                    <h5>
                        @Model.ContentCreateGroup[CreateGroupContent.Image]:</h5>
                </div>
                <div class="divCellRight">
                    <input type="file" name="Image" />
                    <br />
                    <span style="font-style: italic;">@Model.ContentCreateGroup[CreateGroupContent.UploadAnImageToRepresentYourGroup]</span>
                </div>
            </div>
            <div class="divRow">
                <div class="divCell">
                    <h5>
                        @Model.ContentCreateGroup[CreateGroupContent.Privacy]:</h5>
                </div>
                <div class="divCellRight">
                    <ul class="ulSocialSearch">
                        <li>
                            <input id="Privacy" type="radio" name="Privacy" @(!Model.GroupVM.Group.IsPrivate ? Html.Raw("checked='checked'") : MvcHtmlString.Empty) value="Public" /><span>
                                @Model.ContentCreateGroup[CreateGroupContent.Public] </span><span style="font-style: italic;">
                                    @Model.ContentCreateGroup[CreateGroupContent.AnyoneCanSearchForAndJoinThisGroup]</span>
                        </li>
                        <li>
                            <input type="radio" id="Privacy" name="Privacy" @(Model.GroupVM.Group.IsPrivate ? Html.Raw("checked='checked'") : MvcHtmlString.Empty) value="Private" /><span>
                                @Model.ContentCreateGroup[CreateGroupContent.Private]</span><span style="font-style: italic;">
                                    @Model.ContentCreateGroup[CreateGroupContent.OnlyInvitedMembersCanJoinThisGroup]</span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="divRow">
                <div class="divCell">
                    <h5>
                        @Model.ContentCreateGroup[CreateGroupContent.Category]:
                    </h5>
                </div>
                <div class="divCellRight">
                    @Html.DropDownListFor(c => c.GroupVM.Group.CategoryId, new SelectList(Model.Categories, "GroupCategoryId", "GroupCategoryName", Model.GroupVM.Group.CategoryId), "Select one", new { id = "CategoryId", Name = "CategoryId" })
                </div>
            </div>
            <div class="divRow">
                <div class="divCell">
                    <h5>
                        @Model.ContentCreateGroup[CreateGroupContent.Description]:</h5>
                </div>
                <div class="divCellRight">
                    <textarea id="txtDescription" rows="6" name="Description" style="width: 400px; overflow: auto">@Model.GroupVM.Group.Description</textarea>
                </div>
            </div>
        </div>
        }
        if (Model.Mode == "Edit" || Model.Mode == "Create_1")
        {
            if (Model.Mode == "Create_1")
            {
                        
        <div>
            <h4 class="blue">
                @Model.ContentGroupCreated[CGYourGroupHasBeenCreatedContent.YourGroupHasBeenCreated]</h4>
            <p id="pInviteMessage" vlc_name="pInviteMessage">
                @Model.ContentGroupCreated[CGYourGroupHasBeenCreatedContent.EnterTheNames_GroupWhenYoureF_eenCreated]</p>
        </div>
            }
            else
            {
        <h5>
            Invitation:</h5>
            }
        <br />
        <div id="divInvite">
            @Html.Partial("PartialViews/Invite", Model.Invite)
        </div>
        }
        <div style="clear: both; padding: 15px; margin-bottom: 70px;">
            @if (Model.Mode == "Edit")
            {
                <span class="anchorSpan" id="deleteGroup">@Model.ContentCreateGroup[CreateGroupContent.DeleteThisGroup]
                </span>
            }
            <div style="float: right;">
                <input id="btnCancelGroup" type="button" value="@Model.ContentCommon[CommonLabelsContent.Cancel]" onclick="window.location.href = AppPath+'/social/myGroups'"
                class="vbtn_gray_b_md" name="btnCancelGroup" />
                @if (Model.Mode == "Create")
                {
                    <input id="btnCreateGroup" type="button" value="@Model.ContentCreateGroup[CreateGroupContent.CreateGroup]" class="vbtn_red_b_md"
                    name="btnCreateGroup" />
                }
                @if (Model.Mode == "Edit")
                {
                    <input id="btnSaveSend" type="button" value="@Model.ContentSocial[SocialChallengePromotionLabelsContent.SendAndSave]" class="vbtn_red_b_md" />
                }
                @if (Model.Mode == "Create_1")
                {
                    <input id="btnSend" type="button" value="@Model.ContentGroupCreated[CGYourGroupHasBeenCreatedContent.SendInvites]" class="vbtn_red_b_md" />
                }
            </div>
        </div>
    }
    <div id="importCSV" style="display: none">
        <div>
            @Model.ContentSocial[SocialChallengePromotionLabelsContent.MakeSureYourFileContainsAddresses]
        </div>
        <div style="height: 110px; text-align: center;">
            <div style="height: 20px;">
            </div>
            <form method="POST" enctype="multipart/form-data" id="uploadCSVFile" name="uploadCSVFile">
            <input type="file" name="fileBase" id="fileBase" />
            </form>
            <p style="text-align: left; padding: 10px">
                @Model.ContentGroupCreated[CGYourGroupHasBeenCreatedContent.PleaseNoteTheMoreInviteesOn_TakeToUpload]
                <br />
                @Model.ContentGroupCreated[CGYourGroupHasBeenCreatedContent.ThanksForYourPatience]</p>
        </div>
        <div style="padding: 12px 7px;">
            <img src="/v2/content/images/shared/csv_icon.png">
            <a href="/v2/content/files/Template.csv" target="_blank">@Model.ContentSocial[SocialChallengePromotionLabelsContent.DownloadCsvTemplate]</a>
        </div>
    </div>
</div>

VirginLifecareWeb/VirginLifecareWeb/Views/Social/_GroupLink.cshtml
@model Vhm.Web.Models.ViewModels.Social.GroupVM
@using System.Web.Script.Serialization
@using Vhm.Web.Models.ViewModels.Shared
@using Vhm.Web.Models.ViewModels.Social
@{
    var groupImageUrlTemplate = new HtmlString(Url.Action("GetGroupImage", "PartialView") + "/" + Model.ImageSrc);
}
@if (Model.IsClickable)
{
    if (Model.IsPartOfTheGroup)
    {
        <div class="socialList">
            @{var groupImgURL = string.Format(Model.PrivateViewURL, Model.Group.Id);
              }
            <a id="grImageRedirect" href = @groupImgURL>
                <img class="SocialImg" id="imgProfPic" width="50" alt="@Model.Group.Name" src="@Model.Group.ProfilePicturePath" style="margin: 0 8px 5px 0; padding: 2px; border: 0;"  />
                @if (Model.IsLoggedMemberTheAdmin)
{
    <i class="icon-star adminImg main-theme" style="font-size:14px; text-decoration:none; margin-top:-2px; margin-left:-18px;" id="admImg" alt="@MyGroupsContent.YouAreAnAdministratorOfThisGroup" title="@MyGroupsContent.YouAreAnAdministratorOfThisGroup"></i>
                }
            </a>
        </div>
        <div class="socialList_content">
            <a id="grpNameRedirect" class="tertiary blueLink" href = @groupImgURL>@Model.ShortGroupName</a>
        </div>
    }
    else
    {
        <div class="socialList">
            <a id='grImageHref' onclick=' javascript:VHM.SocialGroups.OpenPublicGroupProfileFromID(@Model.Group.Id);'>
                <img class="SocialImg" id="imgProfPicClickable" alt="@Model.Group.Name" width="50" src="@Model.Group.ProfilePicturePath" />
            </a>
        </div>
        <div class="socialList_content">
            <a id="grpNameHrefClickable" class="tertiary blueLink" onclick ='javascript:VHM.SocialGroups.OpenPublicGroupProfileFromID(@Model.sGroupId);'>@Model.ShortGroupName</a>
        </div>
    }
    <div class="socialList_content_Descr">
        <h6 class="lightGrey" style="float: left; padding-top: 0px; padding-left: 2px; line-height:14px;">@Model.Group.Category</h6>
    </div>
}
else
{
    <div>
        <h5>
            <img src="@Model.Group.ProfilePicturePath" class="SocialImg"  style="margin-left: 5px; margin-right: 5px;" alt="@Model.Group.Name" />
            <span>@Model.Group.Name</span>
        </h5>
    </div>
}