VirginLifecareWeb/VirginLifecareWeb/Controllers/ContentController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using System.Xml;
using Vhm.Web.BL;
using Vhm.Web.DataServices.Adapters;
using Vhm.Web.Models.RepositoryModels;
using Vhm.Web.Models.ViewModels.CmsContent;

namespace VirginLifecareWeb.Controllers
{
    [Authorize]
    public class ContentController : ControllerBase
    {
        #region New Content areas
        public PartialViewResult RichContent(string contentAreaType, bool sponsorSpecific = false)
        {
            long sponsorId = 0;
            if (sponsorSpecific == true)
            {
                SponsorProfile sponsorProfile = GetSponsorProfile();
                sponsorId = sponsorProfile.SponsorID;
            }

            var viewModel = new RichContent();

            if (!String.IsNullOrEmpty(contentAreaType))
            {
                ContentAdapter _contentAdapter = new ContentAdapter();
                var content = _contentAdapter.GetEktronRichContent(contentAreaType, sponsorId, LanguageId);
                viewModel.Title = content.Title;
                viewModel.Html = content.Html;

                if (!string.IsNullOrEmpty(viewModel.Html) && !string.IsNullOrEmpty(content.Html) && content.Html.Contains("{spouseCode}"))
                {
                    Member member = MemberBL.GetMemberById(VhmSession.SessionID, VhmSession.MemberID);
                    viewModel.Html = member != null && member.SpouseCode != null
                                         ? content.Html.Replace("{spouseCode}", member.SpouseCode)
                                         : content.Html.Replace("{spouseCode}", "");
                }

            }
            return PartialView("_HtmlRichContent", viewModel);
        }

        public PartialViewResult LatestMemberEngagementArticle(string contentAreaType, bool sponsorSpecific = false)
        {
            long sponsorId = 0;
            if (sponsorSpecific == true)
            {
                SponsorProfile sponsorProfile = GetSponsorProfile();
                sponsorId = sponsorProfile.SponsorID;
            }

            var viewModel = new MemberEngagementArticle();


            if (!String.IsNullOrEmpty(contentAreaType))
            {
                ContentAdapter _contentAdapter = new ContentAdapter();
                List<EktronRichContent> contentList = new List<EktronRichContent>();
                contentList = _contentAdapter.GetSponsorLatestBlogPosts(contentAreaType, sponsorId, LanguageId, 1);

                if (contentList.Count > 0)
                {

                    XmlDocument doc = new XmlDocument();
                    try
                    {
                        doc.LoadXml(contentList[0].Html);
                        viewModel.Title = doc.SelectSingleNode("/ArticleBlog/Title").InnerText;
                        viewModel.Summary = doc.SelectSingleNode("/ArticleBlog/IntroductionText").InnerXml.ToString();
                        viewModel.FullText = doc.SelectSingleNode("/ArticleBlog/FullText").InnerXml.ToString();
                        viewModel.PreviewImageUrl = doc.SelectSingleNode("/ArticleBlog/PreviewImageUrl").InnerXml.ToString();
                        viewModel.FullArticleImageUrl = doc.SelectSingleNode("/ArticleBlog/FullArticleImageUrl").InnerXml.ToString();
                        viewModel.GoogleAnalyticsTrackingCode = doc.SelectSingleNode("/ArticleBlog/GoogleAnalyticsTrackingCode").InnerXml.ToString();
                        viewModel.Id = contentList[0].Id;
                        viewModel.ThemeColor = doc.SelectSingleNode("/ArticleBlog/Color").InnerXml.ToString();
                        viewModel.HideReadMoreLink = doc.SelectSingleNode("/ArticleBlog/HideReadMore").InnerXml.ToString();
                        viewModel.CustomLinkText = doc.SelectSingleNode("/ArticleBlog/CustomReadMore/a").InnerXml.ToString();
                        
                        if (String.IsNullOrEmpty(doc.SelectSingleNode("/ArticleBlog/CustomReadMore/a").Attributes["href"].Value))
                            viewModel.CustomLinkUrl = doc.SelectSingleNode("/ArticleBlog/CustomReadMore/a").Attributes["href"].Value;


                        viewModel.DateCreated = contentList[0].DateCreated;
                    }
                    catch (Exception ex)
                    {
                    }

                }
            }
            return PartialView("_MemberEngagementLeftFooterBanner", viewModel);
        }

        public ViewResult Engagement(long id)
        {
            var viewModel = new MemberEngagementArticle();

            ContentAdapter _contentAdapter = new ContentAdapter();
            EktronRichContent content = new EktronRichContent();
            content = _contentAdapter.GetBlogPostById(id, LanguageId);

            if (content != null)
            {
                XmlDocument doc = new XmlDocument();
                try
                {
                    doc.LoadXml(content.Html);
                    viewModel.Title = doc.SelectSingleNode("/ArticleBlog/Title").InnerText;
                    viewModel.Summary = doc.SelectSingleNode("/ArticleBlog/IntroductionText").InnerXml.ToString();
                    viewModel.FullText = doc.SelectSingleNode("/ArticleBlog/FullText").InnerXml.ToString();
                    viewModel.PreviewImageUrl = doc.SelectSingleNode("/ArticleBlog/PreviewImageUrl").InnerXml.ToString();
                    viewModel.FullArticleImageUrl = doc.SelectSingleNode("/ArticleBlog/FullArticleImageUrl").InnerXml.ToString();
                    viewModel.Id = content.Id;
                    viewModel.DateCreated = content.DateCreated;
                }
                catch (Exception ex)
                {
                }

            }


            return View("MemberEngagementArticle", viewModel);
        }

        public ViewResult BlogArticle(long id)
        {
            var viewModel = new BlogArticle();

            ContentAdapter _contentAdapter = new ContentAdapter();
            EktronRichContent content = new EktronRichContent();
            content = _contentAdapter.GetBlogPostById(id, LanguageId);

            if (content != null)
            {

                BlogArticle blogArticleContent = new BlogArticle();
                XmlDocument doc = new XmlDocument();
                try
                {
                    doc.LoadXml(content.Html);
                    blogArticleContent.Title = doc.SelectSingleNode("/ArticleBlog/Title").InnerText;
                    blogArticleContent.Summary = doc.SelectSingleNode("/ArticleBlog/IntroductionText").InnerXml.ToString();
                    blogArticleContent.FullText = doc.SelectSingleNode("/ArticleBlog/FullText").InnerXml.ToString();
                    blogArticleContent.ImgUrl = doc.SelectSingleNode("/ArticleBlog/Image/img/@src").Value.ToString();
                    blogArticleContent.Id = content.Id;
                    blogArticleContent.DateCreated = content.DateCreated;
                    viewModel = (blogArticleContent);
                }
                catch (Exception ex)
                {
                }

            }


            return View("BlogPost", viewModel);
        }

        public ViewResult LatestBlogPosts(bool sponsorSpecific = false, int count = 3)
        {
            long sponsorId = 0;
            if (sponsorSpecific == true)
            {
                SponsorProfile sponsorProfile = GetSponsorProfile();
                sponsorId = sponsorProfile.SponsorID;
            }

            var viewModel = new BlogList();
            viewModel.Articles = new List<BlogArticle>();

            ContentAdapter _contentAdapter = new ContentAdapter();
            List<EktronRichContent> contentList = new List<EktronRichContent>();
            contentList = _contentAdapter.GetSponsorLatestBlogPosts("BlogPost", sponsorId, LanguageId, count);

            if (contentList != null && contentList.Any())
            {
                foreach (var item in contentList)
                {
                    BlogArticle blogArticleContent = new BlogArticle();
                    XmlDocument doc = new XmlDocument();
                    try
                    {
                        doc.LoadXml(item.Html);
                        blogArticleContent.Title = doc.SelectSingleNode("/ArticleBlog/Title").InnerText;
                        blogArticleContent.Summary = doc.SelectSingleNode("/ArticleBlog/IntroductionText").InnerXml.ToString();
                        blogArticleContent.FullText = doc.SelectSingleNode("/ArticleBlog/FullText").InnerXml.ToString();
                        blogArticleContent.ImgUrl = doc.SelectSingleNode("/ArticleBlog/Image/img/@src").Value.ToString();
                        blogArticleContent.Id = item.Id;
                        blogArticleContent.DateCreated = item.DateCreated;
                        viewModel.Articles.Add(blogArticleContent);
                    }
                    catch (Exception ex)
                    {
                    }
                }
            }


            return View("BlogListPage", viewModel);
        }
        #endregion

        #region Old Landing Page Content

        public PartialViewResult OldLandingTwoByTwo(string contentAreaType, bool sponsorSpecific = false)
        {
            long sponsorId = 0;
            if (sponsorSpecific == true)
            {
                SponsorProfile sponsorProfile = GetSponsorProfile();
                sponsorId = sponsorProfile.SponsorID;
            }

            var viewModel = new OldLandingTwoByTwo();


            if (!String.IsNullOrEmpty(contentAreaType))
            {
                ContentAdapter _contentAdapter = new ContentAdapter();
                EktronRichContent content = new EktronRichContent();

VirginLifecareWeb/VirginLifecareWeb/Controllers/NutritionController.cs
using System.Web.Mvc;
using Vhm.Web.Models.RepositoryModels;
using Vhm.Web.Models.ViewModels.Shared;

namespace VirginLifecareWeb.Controllers
{
    public class Model
    {
        public ColorTheme ThemeCode { get; set; }
    }

    public class NutritionController : ControllerBase
    {
        public NutritionController()
        {
        }

        [ErrorHandle(Action = "Error")]
        public ActionResult LandingPage()
        {
            var model = new Model()
            {
                ThemeCode = GetSelectedTheme()
            };

            ViewData["pageTitle"] = new PageTitle
            {
                PageTitleName = "Nutrition",
                RightLinkText = string.Empty,
                ShowPageTitle = true,
                ShowRightTitleLink = false
            };
            return View(model);
        }
    }
}

VirginLifecareWeb/VirginLifecareWeb/Views/Nutrition/LandingPage.cshtml
@using System.Web.Optimization
@{
    ViewBag.Title = "Nutrition";
    Layout = "~/Views/Shared/MasterNoCol.cshtml";
}
@section Styles
{
    @Styles.Render("~/Content/nutrition")
    <link rel="stylesheet" type="text/css" href="~/Content/style/font-awesome.css" />
    <!--[if IE 7]>
    <link rel="stylesheet" type="text/css" href="/styles/font-awesome-ie7.css" />
    <![endif]-->
    }
@section Script
{
<script type="text/javascript">(function () { var walkme = document.createElement('script'); walkme.type = 'text/javascript'; walkme.async = true; walkme.src = 'https://d3b3ehuo35wzeh.cloudfront.net/users/0ea1430813424357988a7d2edefb7e14/walkme_0ea1430813424357988a7d2edefb7e14_https.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(walkme, s); })();</script>

    @Scripts.Render("~/bundles/nutrition")
    <script type="text/javascript" src="/JavaScript/lib/highcharts.js"></script>
    <script type="text/javascript" src="https://assets­-ssl.myfitnesspal.com/javascripts/mfp.1.0.0.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            window.Nutrition.getActivitySummaries();
        });
    </script>


    <div id="mfp­root"></div>
}



<div class="span6" id="nutrition-content" style="display: block;">

    <div class="overlayMFPConnect">

    </div>
    <div class="overlayMFPConnectContainer" style="display: none;">
        <div class="overlayMFPConnectTopContainer">
            Connect your Pulse and MyFitnessPal accounts to see how your nutrition stacks up (and earn rewards!)<br /><br />
            Don't have a MyFitnessPal account? It's free!
            <button class="btn yellow-custom" id="connectMFPAccount" onclick="TrackGoogleAnalyticEvent('Nutrition', 'Click', 'Connect or sign up to MyFitnessPal');">Connect or sign up to MyFitnessPal</button>
            <div class="importantMFP"><strong>IMPORTANT: </strong>If you're new to MyFitnessPal, you'll need to come on back and click the button above to connect your accounts after you sign up.</div>
        </div>
        <div class="overlayMFPConnectTopBorder"></div>
        <div class="overlayMFPConnectBottomContainer">
            <strong>About this program:</strong> Studies have shown that simply writing down the food you
            eat encourages you to eat fewer calories, which is key to managing or losing
            weight. Yet without the right tools, tracking calories can be tedious or simply
            impossible to keep up. That's why Virgin Pulse has teamed up with MyFitnessPal,
            marrying the world's two leading health and fitness systems to deliver more
            information, great tips, and even better results.
        </div>
    </div>
    <h1 class="accent-theme underline">Calorie Tracking and Weight Management
        <a href="#helpModalNutrition" data-toggle="modal" class="helpLinkNutrition" title="My Daily Calorie Balance Chart">
            <i class="icon-question"></i>
        </a>
    </h1>
    <div id="loading-element"></div>
    <p id="nut-loading"></p>
    
    @Html.Partial("_TrackingWidget")
    <hr style="margin: 30px 0;" />
    
    @Html.Partial("_WeightGoalDialog")

    
    <div>
        @Html.Action("RichContent", "Content", new { @contentAreaType = "NutritionLandingTop", @sponsorSpecific = true })
    </div>
      
    <div>
        @Html.Action("RichContent", "Content", new { @contentAreaType = "NutritionLandingBottom", @sponsorSpecific = true })
    </div>
</div>
<div class="span3 side-nav">
    <div style="width: 280px;">
        <div id="nutrition-progress-wrapper" style="display:block;">
            <!-- My Progress chart -->
            @Html.Partial("_ProgressWidget")
        </div>
            <!-- Data Provider connection status -->
            @Html.Partial("_ConnectionWidget")

            <!-- What is next - rewards nutrition -->
            @Html.Partial("_WhatsNextWidget")

            <!-- My friends -->
            @Html.Partial("_MyFriendsWidget")

            <!-- Challenge Widget -->
            @Html.Partial("_ChallengeList")
        </div>
    
</div>

@Html.Partial("_GuidedGoal")

<div id="helpModalNutrition" class="modal hide fade helpNlast">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h2 class="main-theme underline helpModalTitle  first-head">WHAT ‘CALORIES REMAINING’ MEANS:</h2>
    <div class="helpModalContent">
        This is an important number to watch, because it shows you the number of calories you have remaining for the day, or the number of calories you went over that day, to hit your daily calorie goal. It’s calculated by taking your NET CAL number (which is the number of calories you’ve eaten, minus the number of calories you’ve burned) and subtracting it from your daily calorie goal. The number will change throughout the day as your track your food intake and upload or enter activity.
    </div>
    <h2 class="main-theme underline helpModalTitle">HOW WE CALCULATE YOUR DAILY CALORIE GOAL</h2>
    <div class="helpModalContent">
        We start with your Resting Metabolic Rate (RMR), which is the number of calories your body will burn if you get no exercise. Next, we factor in your 14-day average calorie burn, based on all
        the physical activity you do. (For new members, we estimate your activity until you have some in the system.) Then, we add or subtract the number of calories that correspond to your weight-change goal. The result is your daily calorie goal.
    </div>
    <h2 class="main-theme underline helpModalTitle">WHY YOUR NUMBERS ARE DIFFERENT THAN MYFITNESS PAL</h2>
    <div class="helpModalContent">
        Virgin Pulse and MyFitnessPal calculate your daily calorie goal a little differently, which is why you may see some differences between the two systems. At Virgin Pulse, we factor in the actual number of calories you’re burning through exercise (either uploaded through your device, or manually entered in your Activity Journal), using a 14-day rolling average. MyFitnessPal factors in a number of calories burned that’s based on the activity level you chose when you set up your account, not necessarily the calories you’re actually burning through exercise.
    </div>
    <h2 class="main-theme underline helpModalTitle">RESTING METABOLIC RATE (RMR)</h2>
    <div class="helpModalContent">
        Virgin Pulse calculates your Resting Metabolic Rate (RMR) that considers your weight, age, gender and height using the Mifflin St. Joer algorithm which is the most accurate and/or underestimates RMR in some cases; which we believe to be beneficial to those interested in managing weight. The RMR estimates the number of calories an individual will burn with zero physical activity (resting) for a 24 hour period.
    </div>
    <h2 class="main-theme underline helpModalTitle">MACRONUTRIENTS</h2>
    <div class="helpModalContent">
        We start with the most accurate Resting Metabolic Rate (RMR). This is the number of calories your body will burn with zero exercise. Next, we add some estimated activity calories to your RMR to arrive at your base daily calories*. Next we subtract or add a number of calories that correspond to your weight change goal. The result is your daily calorie budget goal.<br /><br />
        The Nutrition display will change as you upload exercise, or track food calories each day to show progress against your daily budget.<br /><br />
        *Virgin Pulse uses your real, validated activity data to set the daily budget. For current Virgin Pulse members, we will take your current 14 day average daily activity calories when we calculate the daily calorie budget. If you are a new member, we will include an estimate until you have some real activity data in the system.
    </div>
</div>
<script type="text/javascript">
    var fby = fby || [];
    fby.push(['showTab', { id: '5949', position: 'right', color: '#008EAA'}]);
    (function () {
        var f = document.createElement('script'); f.type = 'text/javascript'; f.async = true;
        f.src = '//cdn.feedbackify.com/f.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(f, s);
    })();
</script>
@{
    string trackerKey = Convert.ToString(Microsoft.Win32.Registry.LocalMachine.OpenSubKey(@"Software\VirginLifecare", false).GetValue("GoogleAnalyticsId", "")) == string.Empty ? "UA-5511099-1" : Convert.ToString(Microsoft.Win32.Registry.LocalMachine.OpenSubKey(@"Software\VirginLifecare", false).GetValue("GoogleAnalyticsId", ""));
}
 <script type="text/javascript">

     var _gaq = _gaq || [];
     _gaq.push(['_setAccount', '@trackerKey']);
     _gaq.push(['_trackPageview']);

     (function () {
         var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
         ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
         var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
     })();

 </script>

VirginLifecareWeb/VirginLifecareWeb/Views/Nutrition/_ChallengeList.cshtml
<div id="nutrition-challenge-list" class="hide" data-bind="if: HasChallenges">
    <h2 class="accent-theme header">
        Join a Challenge</h2>
    <div id="nutChallengeList" data-bind="template: { name: 'challenge-list-template', 'foreach': Challenges }">
    </div>
</div>
<script type="text/html" id="challenge-list-template">
    <div class="challenge-list-item">
        <div class="challengeBadge">              
            <span data-bind="if: BadgeImageUrl"><img data-bind="attr: {'src': BadgeImageUrl }" /></span>
        </div>
        <div class="challengeItem">
            <p class="challenge-item-title"><strong><span data-bind="text: Name"></span></strong></p>
            <p class="challenge-member-participation" data-bind="if: ParticipantCount"><span data-bind="text: ParticipantCount"></span> members</p>
            <p class="challenge-item-description" data-bind="if: Description"><span data-bind="text: Description"></span></p>
            <div class="challenge-item-join" data-bind="if: ChallengeUrl"><a data-bind="attr: {'href': ChallengeUrl }">Join now!</a></div>
        </div>    
        <div class="clearfix"></div>      
    </div>   
</script>

VirginLifecareWeb/VirginLifecareWeb/Views/Nutrition/_ConnectionWidget.cshtml
<div id="nutrition-partner-connect" class="content-box hide">
    <img class="logo" src="/v2/Content/Images/Nutrition/myfitnesspal.png" width="232" height="50" alt="MyFitnessPal" />
    <div class="status hide">
        <h4 class="grey">Status: <span class="status-label status-connected"><i class='icon-ok'></i> Connected</span></h4>
        <p><a class="tertiary" href="/rest/v1/nutrition/data-providers/mfp/website" target="_blank" onclick="TrackGoogleAnalyticEvent('Nutrition', 'Click', 'Go to MyFitnessPal');">Go to MyFitnessPal</a></p>
        <p><a class="btn-disconnect tertiary" href="#" title="Stops sharing information with MyFitnessPal">Disconnect</a></p>
        <p><a class="btn-refresh tertiary" href="#" title="Sends activity data to MyFitnessPal and retrieves the latest consumption data from there">Refresh</a></p>
        <p><span class="btn-refreshing tertiary" href="#"><img src="/v2/Content/Images/Nutrition/refreshing.gif" width="16" height="16" /> Refreshing...</span></p>
        <p><button class="btn btn-main btn-small btn-connect" onclick="TrackGoogleAnalyticEvent('Nutrition', 'Click', 'Connect to MyFitnessPal');">Connect to MyFitnessPal</button></p>
    </div>
</div>

VirginLifecareWeb/VirginLifecareWeb/Views/Nutrition/_GuidedGoal.cshtml
<div id="nutrition-weight-guided-dlg" class="modal hide fade">
    <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <div id="guided-goal-step1">
            <h2 class="main-theme">Edit goal: Guide me</h2>
            <p class="margb25px">Do you want to lose, maintain, or gain weight?</p>
            <form class="form-horizontal">
                <div class="step1-goal-type">
                    <div class="control-group">
                        <input type="radio" name="guided_weight" id="loseWeight" class="guided-goal-input">
                        <label for="loseWeight" class="accent-theme tungsten-small guided-goal-label">I want to lose weight</label>
                    </div>
                    <div class="control-group">
                        <input type="radio" name="guided_weight" id="maintainWeight" class="guided-goal-input">
                        <label for="maintainWeight" class="accent-theme tungsten-small guided-goal-label">I want to maintain weight</label>
                    </div>
                    <div class="control-group">
                        <input type="radio" name="guided_weight" id="gainWeight" class="guided-goal-input">
                        <label for="gainWeight" class="accent-theme tungsten-small guided-goal-label">I want to gain weight</label>
                    </div>
                    <div class="control-group margt45px div-currentweight hide">
                        <label class="weight-label-inputs accent-theme tungsten-small" for="current-weight">What is your current weight?</label>
                        <div class="controls">
                            <input value="" type="number" min="80" max="400" maxlength="3" id="guided-current-weight" /><span class="help-inline">lbs</span>
                        </div>
                    </div>
                    <div class="control-group margb45px div-howmuchtolose hide">
                        <label class="weight-label-inputs accent-theme tungsten-small " for="lose-weight">What is your target weight?</label>
                        <div class="controls">
                            <input value="" type="number" min="80" max="400" maxlength="3" id="lose-gain-weight" /><span class="help-inline">lbs</span>
                        </div>
                    </div>
                </div>
            </form>
            <div>
                <input type="button" class="btn button-save yellow-button" id="guided-goal-step1-next" value="Next" />
                <button type="button" class="btn grey-button" data-dismiss="modal" aria-hidden="true">Cancel</button>
            </div>
        </div>
        <div id="guided-goal-step2" style="display:none;">
            <h2 class="main-theme">Edit goal: Guide me</h2>
            <p class="margb25px">At what pace do you want to <span class="lose-gain-label">lose</span> weight?</p>
            <form class="form-horizontal">
                <div class="control-group">
                    <input type="radio" name="guided_weight" id="loseItEasyWeight" class="guided-goal-input">
                    <label for="loseItEasyWeight" class="accent-theme tungsten-small guided-goal-label weight-intesity-label weight-intesity-labels"></label>
                    <div class="weight-intensity-note"><span class="lose-gain-caps-label">Lose</span> <strong>.5 pounds</strong> a week</div>
                    
                </div>
                <div class="control-group">
                    <input type="radio" name="guided_weight" id="loseItModerateWeight" class="guided-goal-input">
                    <label for="loseItModerateWeight" class="accent-theme tungsten-small guided-goal-label weight-intesity-label weight-intesity-labels"></label>
                    <div class="weight-intensity-note"><span class="lose-gain-caps-label">Lose</span> <strong>1 pound</strong> a week</div>
                  
                </div>
                <div class="control-group">
                    <input type="radio" name="guided_weight" id="loseItAgressivesWeight" class="guided-goal-input">
                    <label for="loseItAgressivesWeight" class="accent-theme tungsten-small guided-goal-label weight-intesity-label weight-intesity-labels"></label>
                    <div class="weight-intensity-note"><span class="lose-gain-caps-label">Lose</span> <strong>1.5 pounds</strong> a week</div>
                  
                </div>
                <div class="control-group">
                    <input type="radio" name="guided_weight" id="loseItIntenseWeight" class="guided-goal-input">
                    <label for="loseItIntenseWeight" class="accent-theme tungsten-small guided-goal-label weight-intesity-label weight-intesity-labels"></label>
                    <div class="weight-intensity-note"><span class="lose-gain-caps-label">Lose</span> <strong>2 pounds</strong> a week</div>
                    
                </div>
                <input type="hidden" value="0" id="weight-goal-value"/>
            </form>
            <p class="content">
                <input type="button" class="btn button-save yellow-button" id="guided-goal-step2-next" value="Next" />
                <input type="button" class="btn grey-button" id="guided-goal-step2-back" value="Back" />
            </p>
        </div>
        <div id="guided-goal-step3" style="display:none;">
            <h2 class="main-theme">Edit goal: Guide me</h2>
            <p class="margb25px">
                Give us your current weight, goal weight, and the rate at which you want to lose or gain weight. We’ll factor in your 14-day average daily calorie burn (based on your activity device or manual entries), and then calculate your daily calorie goal.
            </p>
            <div class="control-group margb15px">
                <div class="weight-label-inputs accent-theme tungsten-small weight-final-step-label">Current weight:</div>
                <div class="weight-final-step-value" id="nutrition-current-weight-value"><span class="value"></span> lbs</div>
            </div>
            <div class="control-group margb15px">
                <div class="weight-label-inputs accent-theme tungsten-small weight-final-step-label">Goal:</div>
                <div class="weight-final-step-value" id="nutrition-lose-weight-value"><span class="value"></span> lbs</div>
            </div>
            <div class="control-group margb15px weeklyweightgoal">
                <div class="weight-label-inputs accent-theme tungsten-small weight-final-step-label">Weekly weight <span class="lose-gain-caps-label-step3">loss</span> goal:</div>
                <div class="weight-final-step-value" id="nutrition-weekly-loss-weight-value"><span class="value"></span> lbs</div>
            </div>
            <div class="control-group margb15px">
                <div class="weight-label-inputs accent-theme tungsten-small weight-final-step-label">Daily calorie goal:</div>
                <div class="weight-final-step-goal-value" id="nutrition-daily-calories-goal"></div>
            </div>
            <div class="control-group margb45px timetogoal">
                <div class="weight-label-inputs accent-theme tungsten-small weight-final-step-label">Time to goal weight:</div>
                <div class="weight-final-step-goal-value" id="nutrition-weekly-goal-weight"></div>
            </div>
            <div class="goal-warning">
                <p>
                    This is a very helpful tool, but don’t let it replace the advice of your doctor.
                </p>
            </div>
            <div class="weight-intensity-note margb25px">Don't like this? <a class="try-doing-yourself-dialog">Try doing it yourself</a></div>
            <p class="weight-save-container">
                <input type="button" class="btn button-save yellow-button" id="guided-goal-step3-save" value="Save" />
                <input type="button" class="btn grey-button" id="guided-goal-step3-back" value="Adjust my numbers" />
            </p>
        </div>
    </div>
</div>

VirginLifecareWeb/VirginLifecareWeb/Views/Nutrition/_WhatsNextWidget.cshtml
<div id="nutritionRewards" class="content-box hide" style="margin-top: 30px; width: 259px;">
    <h2 class="main-theme">What's next</h2>
    <ul class="rewards-content" style="list-style: none; padding-left: 0px">
    </ul>
</div>