VirginLifecareWeb/VirginLifecareWeb/Controllers/LayoutController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using Vhm.Providers;
using Vhm.Web.BL;
using Vhm.Web.Common;
using Vhm.Web.Models.Enums;
using Vhm.Web.Models.RepositoryModels;
using Vhm.Web.Models.ViewModels.Shared;
using VirginLifecareWeb.Controllers.ActionResults;
using VirginLifecare.Utils;
using System.Configuration;

namespace VirginLifecareWeb.Controllers
{
    [Authorize]
    public class LayoutController : ControllerBase
    {
        public bool EnableNewLanding
        {
            get
            {
                if (VhmSession == null || string.IsNullOrEmpty(VhmSession.SessionID))
                {
                    return false;
                }

                #region check if is express test sponsor
                var member = MemberBL.GetMemberById(VhmSession.SessionID, VhmSession.MemberID);
                var game = RewardsBL.GetSponsorCurrentGame(VhmSession.SessionID, member, VhmSession.PrimarySponsorID);
                if (game != null && game.ProgramType == "EXP")
                {
                    return true;
                }
                #endregion
                string[] betaUIForSponsor = ConfigurationManager.AppSettings["BetaUIForSponsor"].Split(',');
                bool useNewLandingPage = false;
                var httpCookie = Request.Cookies["NewLanding" + VhmSession.MemberID.ToString()];

                useNewLandingPage = betaUIForSponsor.Any(s => s == VhmSession.PrimarySponsorID.ToString());

                if (httpCookie != null && !string.IsNullOrEmpty(httpCookie.Value) && useNewLandingPage)
                {
                    if (httpCookie.Value == "yes")
                    {
                        ViewBag["EnableNewLanding"] = true;
                        return true;
                        
                    }
                    ViewBag["EnableNewLanding"] = false;
                    return false;
                }
                ViewBag["EnableNewLanding"] = false;
                return false;
            }
        }
        private Dictionary<HeaderContent, string> GetHeaderContent()
        {

            var headerContent = MemberBL.GetContentLabels<HeaderContent>(PageNames.PageHeader, LanguageId);

            return headerContent;
        }

        public ActionResult Header()
        {
            var viewModel = new HeaderViewModel();

            SponsorProfile = GetSponsorProfile();
            //the default Standard red color theme
            var selectedColorTheme = new ColorTheme { ColorThemeCode = "red", ColorThemeName = "Standard Red", BrandingThemeId = 1, isDefault = true };
            if (VhmSession.PrimarySponsorID > 0)
            {
                selectedColorTheme = ColorThemes.FirstOrDefault(ct => ct.BrandingThemeId == SponsorProfile.BrandingThemeID);
            }
            viewModel.ThemeCode = selectedColorTheme;

            var count = SocialBL.GetMemberNotificationCount(VhmSession.MemberID);
            viewModel.UnreadNotificationCount = count;

            var headerContent = GetHeaderContent();

            // Try to get the main menu from cache. If not there, rebuild it from the database and store it in cache.
            var mainMenu = CacheProvider.Get(System.Web.HttpContext.Current, CacheProvider.CacheItems.MvcMenu) as MainMenuItem;
            if (mainMenu != null)
            {
                viewModel.MainMenu = mainMenu;
                viewModel.Content = headerContent;
            }
            else
            {
                #region Build main menu

                var modules = GetModules();
                viewModel.Content = headerContent;

                var challenges = MemberBL.GetMemberChallenges(VhmSession.MemberID, VhmSession.PrimarySponsorID, ApplicationSettings.ChallengeEndedDisplayDays, VhmSession.LanguageID);
                var crpChallenges = new List<ChallengeBase>();
                crpChallenges.AddRange(challenges);
                CacheProvider.Update(System.Web.HttpContext.Current, CacheProvider.CacheItems.CorporateChallenges, crpChallenges);
                
                bool hasBrowseChallenges = false;
                try
                {
                    hasBrowseChallenges = challenges.Any( c => c.ShowInBrowseOnly );
                    // remove corporate tracking challenges for which the member has not yet signed up
                    challenges.RemoveAll(c => c.ShowInBrowseOnly && !c.IsMemberEnrolled);

                    CacheProvider.Update(System.Web.HttpContext.Current, CacheProvider.CacheItems.MemberChallenges, challenges);
                }
                catch (Exception ex)
                {
                    VirginLifecare.Exception.ExceptionHandler.ProcessException(ex);
                    challenges = new List<ChallengeBase>();
                }
                
                challenges = challenges.Where(c => c.MenuDisplay).ToList();

                var personChallValue = modules.Count(m => m.ModuleID == -1) > 0;

                var dsMenu = CacheProvider.Get(System.Web.HttpContext.Current, CacheProvider.CacheItems.MainMenu) as DataSet;
                if (dsMenu == null)
                {
                    dsMenu = InitMenuDataSet(modules, headerContent);
                    using (var dt = dsMenu.Tables[1])
                    {
                        var arrChallengeMenuItems = GetChallengeMenuItems(personChallValue, challenges, headerContent, modules, hasBrowseChallenges);

                        foreach (object t in arrChallengeMenuItems)
                        {
                            var challengeMenuItem = (ChallengeMenuItem)t;
                            var nrq = dt.NewRow();
                            nrq["Name"] = challengeMenuItem.CodeName;
                            nrq["Desc"] = challengeMenuItem.Name;
                            nrq["NavUrl"] = challengeMenuItem.Link;
                            nrq["NavCategory_Id"] = 3;
                            dt.Rows.Add(nrq);
                        }
                    }
                    CacheProvider.Update(System.Web.HttpContext.Current, CacheProvider.CacheItems.MainMenu, dsMenu);
                }

                mainMenu = BuildMenuItems(dsMenu, headerContent);
                viewModel.MainMenu = mainMenu;

                

                CacheProvider.Update(System.Web.HttpContext.Current, CacheProvider.CacheItems.MvcMenu, mainMenu);
                #endregion
            }
            #region Build the Branding section
            //make sure profile exists
            if (SponsorProfile != null && SponsorProfile.SponsorID == VhmSession.PrimarySponsorID)
            {
                if (SponsorProfile.UseCustomBrand)
                {
                    #region build sponsor logo, if any available from database
                    //populate the Use custom brand properties
                    if (SponsorProfile.LogoType != null && SponsorProfile.SponsorLogo != null && SponsorProfile.SponsorLogo.Length > 1)
                    {
                        //if sponsor has a logo uploaded in database
                        if (SponsorProfile.LogoType == SponsorLogoType.TXT || SponsorProfile.LogoType == SponsorLogoType.TEXT)
                        {
                            viewModel.SponsorImageUrl = string.Empty;
                            viewModel.SponsorLogoType = "text";
                            viewModel.SponsorText = Encoding.ASCII.GetString(SponsorProfile.SponsorLogo);
                        }
                        else //it can only be an image if not text
                        {
                            //pass random parameter to prevent cached data
                            viewModel.SponsorImageUrl = "/v2/Image/LogoDisplay?r=" + DateTime.Now.Ticks;
                            viewModel.SponsorLogoType = "image";
                            viewModel.SponsorText = string.Empty;
                        }
                    }
                    #endregion
                }
                else
                {
                    #region build VHM logo link and check if sponsor has "Brought to you by"
                    #region check if brought to you by and populate properties
                    if (SponsorProfile.LogoType != null && SponsorProfile.SponsorLogo != null && SponsorProfile.SponsorLogo.Length > 1)
                    {
                        viewModel.SponsorDefaultBroughtToYouByText =
                            headerContent[HeaderContent.BroughtToYouBy];

                        //if sponsor has a logo uploaded in database
                        viewModel.ShowBroughtToYouBy = true;
                        if (SponsorProfile.LogoType == SponsorLogoType.TXT || SponsorProfile.LogoType == SponsorLogoType.TEXT)
                        {
                            viewModel.SponsorBroughtToYouByUrl = string.Empty;
                            viewModel.SponsorBroughtToYouByText = Encoding.ASCII.GetString(SponsorProfile.SponsorLogo);
                            viewModel.SponsorLogoType = "text";
                        }
                        else //it can only be an image if not text
                        {
                            //pass random parameter to prevent cached data
                            viewModel.SponsorBroughtToYouByUrl = "/v2/Image/LogoDisplay?r=" + DateTime.Now.Ticks;
                            viewModel.SponsorBroughtToYouByText = string.Empty;
                            viewModel.SponsorLogoType = "image";
                        }
                    }
                    else
                    {
                        viewModel.ShowBroughtToYouBy = false;
                        viewModel.SponsorBroughtToYouByUrl = string.Empty;
                        viewModel.SponsorBroughtToYouByText = string.Empty;

VirginLifecareWeb/VirginLifecareWeb/Views/Shared/MasterNoCol.cshtml
@using Vhm.Web.Models.ViewModels.Shared
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Styles
{
    @RenderSection("Styles", false)
}
@section Script
{
    @RenderSection("Script", false)
}
@Html.Action("TitlePageHeader", "Layout", new RouteValueDictionary(new Dictionary<string, object> { { "page", ViewData["pageTitle"] as PageTitle } }))
<div id="wrapper">
    <div class="row">
        <div class="span12">
            @RenderBody()
        </div>
    </div>
</div>

VirginLifecareWeb/VirginLifecareWeb/Views/Shared/MasterThreeCol.cshtml
@using Vhm.Web.Models.ViewModels.Shared
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Styles
{
    @RenderSection("Styles", false)
}
@section Script
{
    @RenderSection("Script", false)
}
<div id="section">
    <div class="VHMwrapperThreeColumn">
        <div class="VHMwrapperB_ThreeColumn" id="pageContentWrapper">
            @Html.Action("TitlePageHeader", "Layout", new RouteValueDictionary(new Dictionary<string, object> {{ "page", ViewData["pageTitle"] as PageTitle }}))
            <div class="leftCol_threeColumn">
                    @RenderSection("LeftColumn", false)
                </div>
                <div class="rightCol_threeColumn">
                    @RenderSection("RightColumn", false)
                </div>
                <div class="main_threeColumn">
                    @RenderBody()
                </div>
        </div>
    </div>
</div>

VirginLifecareWeb/VirginLifecareWeb/Views/Shared/MasterTwoCol.cshtml
@using Vhm.Web.Models.ViewModels.Shared
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Styles
{
    @RenderSection("Styles", false)
}
@section Script
{
    @RenderSection("Script", false)
}
@Html.Action("TitlePageHeader", "Layout", new RouteValueDictionary(new Dictionary<string, object> { { "page", ViewData["pageTitle"] as PageTitle } }))
<div id="wrapper">
        <div class="right_twoColumnLeft">
            @RenderSection("RightColumn", false)
        </div>
        <div class="main_twoColumnLeft">
            <div class="row">
                @RenderBody()
            </div>
        </div>
    <div style="clear: both;">
    </div>
</div>

VirginLifecareWeb/VirginLifecareWeb/Views/Shared/MasterTwoColWide.cshtml
@using Vhm.Web.Models.ViewModels.Shared
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Styles
{
    @RenderSection("Styles", false)
}
@section Script
{
    @RenderSection("Script", false)
}
<div id="section">
    <div class="VHMwrapper">
        <div class="VHMwrapperB" id="pageContentWrapper">
            @Html.Action("TitlePageHeader", "Layout", new RouteValueDictionary(new Dictionary<string, object> {{ "page", ViewData["pageTitle"] as PageTitle }})) 
            <div class="leftCol_twoColumnRight">
                @RenderSection("RightColumn", false)
            </div>
            <div class="main_twoColumnRight">
                @RenderBody()
            </div>
        </div>
    </div>
</div>

VirginLifecareWeb/VirginLifecareWeb/Views/Shared/_Layout.cshtml
@using System.Configuration
@using System.Web.Optimization
@using Vhm.Web.Common
<!DOCTYPE html>
@{
    var resourceVersion = ApplicationSettings.CachedResourceVersion;
    var background = ApplicationSettings.SiteBackgroundURL;
}
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=1024, maximum-scale=1.5" />
    <meta name="keywords" content="@ViewBag.OldSiteUrl, Health, Wellness, Rewards, Incentive, Pedometer, Active, Challenge" />
    <meta name="description" content="@ViewBag.CompanyName is a rewards program that works kind of like a frequent flier program, only you don't get rewarded for flying or using a credit card. You get rewarded for getting active. You get great rewards for making small choices that go a long way toward a healthier you." />
    <title></title>
    @Styles.Render("~/Content/css")
    @RenderSection("Styles", false)

    <link rel="stylesheet" type="text/css" href="@Url.Content(string.Format("~/Content/themes/{0}/css/theme.css?v={1}", @Model.ThemeCode.ColorThemeCode, resourceVersion))" />

    <!--[if IE 9]>
    <link rel="stylesheet" type="text/css" href="~/Content/style/ie9.css" />
    <![endif]-->
    <!--[if IE 8]>
    <link rel="stylesheet" type="text/css" href="~/Content/style/ie8.css" />
    <![endif]-->
    @{
        if (ViewBag.EnableNewLanding)
        {
            <link rel="stylesheet" type="text/css" href="/styles/v3/tungstenV3.css?<%= ResourceVersion %>" />
        }
    }


</head>
<body style="background-image: url('@(Url.Content(string.Format("~/Content/themes/{0}/images/{1}", Model.ThemeCode.ColorThemeCode, background)))');">
    @Html.Action("Header", "Layout")
    @{
        if (ViewBag.ShowBillingInfo)
        {
            <input type="hidden" id="showBillingInfo" value="true" />
            <div id="billingInfo" style="display: none;">
                <p>
                    <span class="content">To continue as a member, you will need to set up a billing method. Please click \"Continue\" to enter new payment details.</span>
                </p>
                <p>
                    <a href="@string.Format("{0}/secure/member/updatecc.aspx", ApplicationSettings.BaseURL)">Continue</a> | <a href=@string.Format("{0}/logout.aspx", ApplicationSettings.BaseURL)>Log out</a>
                </p>
            </div>
        }
    }
    @RenderBody()
    @*@if ( @Request.RawUrl == "/v2/member/landingpage" )
        {
            @Html.Action("FooterLandingPage", "Layout")
        }
        else
        {*@
    @Html.Action("Footer", "Layout")
    @*}*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/vhm")

    <script type="text/javascript">
        (function ($) {
            $(function () {
                var pageWrapper = $('#pageContentWrapper');
                var pageWidth = pageWrapper.width(); //.attr("width");
                //we need to set up the pageTitle width - so, out of the pageWidth we need to take out the width of the background left + right background
                //                    var pageTitleLeft = $(".pageTitleLeft").width();
                //                    var pageTitleRight = $(".pageTitleRight").width();
                var pageTitleCenter = pageWidth; // -pageTitleLeft - pageTitleRight;
                $(".pageTitleCenter").width(pageTitleCenter);
                var div = $('.VHMwrapper');
                div.css({ "min-height": ($(window).height() - $("#header").height()) - $("#footer").height() * 2 });
            });

            var showPopUpForBillingInfo = $('#showBillingInfo').val();
            if (showPopUpForBillingInfo != undefined) {
                if (showPopUpForBillingInfo.toLowerCase() == 'true') {
                    $("#billingInfo").dialog({
                        title: 'Important Account Information',
                        width: '400px',
                        modal: true,
                        resizable: false,
                        closeOnEscape: false,
                        open: function (event, ui) {
                            $(".ui-dialog-titlebar-close").hide();
                        }
                    });
                }
            }
        })(jQuery);
        
    </script>
    @RenderSection("Script", false)
    <script type="text/javascript">
        $(document).ready(function () {
            $('.VHMheadermenuc .main-nav .nav > li.menu-item-li').hover(
               function () { $(this).addClass('active') },
               function () { $(this).removeClass('active') });
        });
    </script>
    <script type="text/javascript">
        //localization plugin init
        i18n.init(function (t) {
            $("body").i18n({ ns: "LocalizationLibrary" });
        });
    </script>
    <script type="text/javascript">
        var AppPath = "@(Html.Raw(Request.Url.Scheme))://@(Html.Raw(Request.Url.Host))" + "/v2";
    </script>
    @{
        string trackerKey = Convert.ToString(Microsoft.Win32.Registry.LocalMachine.OpenSubKey(@"Software\VirginLifecare", false).GetValue("GoogleAnalyticsId", "")) == string.Empty ? "UA-5511099-1" : Convert.ToString(Microsoft.Win32.Registry.LocalMachine.OpenSubKey(@"Software\VirginLifecare", false).GetValue("GoogleAnalyticsId", ""));
    }
    <!-- START Google Analytics  -->
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', '@trackerKey']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
    <!-- END Google Analytics -->
</body>
</html>

VirginLifecareWeb/VirginLifecareWeb/Views/Shared/_NewsFeed.cshtml
@using Vhm.Web.Common
@using Vhm.Web.Models.RepositoryModels
@using Vhm.Web.Models.ViewModels.Social
@model Vhm.Web.Models.ViewModels.Social.NewsFeedVM

@helper PostText(NewsfeedPost post){
    string cdnBaseURL=ApplicationSettings.CDNBaseURL;
    string postText = string.Empty;
    string nfLink = " and&nbsp;<a style=\"padding:0px;\" href=\"" + Model.NewsfeedUrl + "\">" + post.AggregationCount + "&nbsp;others</a>";
    string profileLink = "<a class=\"profileLink\" href=\"#\" memberId=\"" + post.PostById + "\" friendId=\"" + post.PostById + "\">" + post.PostByName + "</a>";
    string friendLink = "<a class=\"profileLink\" href=\"#\"  memberId=\"" + post.PostById + "\" friendId=\"" + post.PostToId + "\">" + post.PostToName + "</a>";
    string badgeLink = "<a href=\"/secure/rewards/mybadges.aspx\">{0}</a>";
    if (post.AggregationCount > 1) {
        switch (post.PostType) {
            case NewsfeedPost.POST_TYPE_FRIEND: // friend
                {

                    postText = post.PostText.Replace("<Member>", profileLink).Replace("<Friend>", friendLink) + nfLink + ".";
                    break;
                }
            case NewsfeedPost.POST_TYPE_JOIN_GROUP: // joined group
                {
                    postText = profileLink + nfLink + " " + Model.Content[NewsFeedContent.HaveJustJoined] + " " +
                               post.GroupName;
                    break;
                }
            case NewsfeedPost.POST_TYPE_PROMO: // promo
                {
                    postText = profileLink + nfLink + " " + post.PostText;
                    post.PostText = postText;
                    break;
                }
            case NewsfeedPost.POST_TYPE_BADGE: // badge
                {
                    postText = profileLink + nfLink + " " + Model.Content[NewsFeedContent.HaveJustEarned] +
                               string.Format(badgeLink, post.BadgeName) + "badge";
                    post.PostText = postText;
                    break;
                }
            default: {
                postText = post.PostText.Replace("<Member>", profileLink).Replace("<Friend>", post.PostToName);
                    break;
                }
        }
    } else
    {
        if (post.PostType == NewsfeedPost.POST_TYPE_BADGE) {
            postText = profileLink + " " + Model.Content[NewsFeedContent.HasJustEarned] + " " +
                               string.Format(badgeLink, post.BadgeName) +  " badge";
        }
        else if (post.PostType == NewsfeedPost.POST_TYPE_MANUAL)
        {
            postText = profileLink + "<br />" + post.PostText;
        } else
        {
            postText = post.PostText.Replace("<Member>", profileLink).Replace("<Friend>", post.PostToName); 
        }
    }
    var htmlPostString = new HtmlString(postText);
    <span>@htmlPostString</span>
}   

@helper PostImage(NewsfeedPost post){
    string image, altText;

    switch (post.PostType)
    {
        case NewsfeedPost.POST_TYPE_JOIN_GROUP: {
                image = post.GroupImage;
                altText = post.GroupName;
                break;
            }
        case NewsfeedPost.POST_TYPE_BADGE:
            {
                image = post.BadgeImage;
                altText = post.BadgeName;
                break;
            }
        default:
            {
                image = post.PostByImage;
                altText = post.PostByName;
                break;
            }
           
    }
    var imgeURL =(ApplicationSettings.BaseURL+image).StartsWith(ApplicationSettings.BuildBadgeImageUrl) || image.StartsWith("http") ? image : ApplicationSettings.CDNBaseURL + image;
    <img src="@imgeURL" alt="@altText" />
}   

@helper LikeText(NewsfeedPost post)
    {
    string likeText = string.Empty;
    if (post.LikeCount > 1)
    {
        likeText = post.YouLikeThis ? string.Format(Model.Content[NewsFeedContent.YouAndNPeopleLike], post.LikeCount) : string.Format(Model.Content[NewsFeedContent.NPeopleLike], post.LikeCount);
    }
    else if (post.YouLikeThis)
    {
        likeText = Model.Content[NewsFeedContent.YouLikeThis];
    }
    else if (post.LikeCount == 1)
    {
        likeText = Model.Content[NewsFeedContent.OnePersonLikes];
        
    }
    if (!string.IsNullOrEmpty(likeText))
    {
        <img class="likeImage" src="/images/social/icon-likes.gif" alt="like" style="width: 16px; height:16px; border:0;" />
    }
    <span class="newsfeedSubText grey">@likeText</span>
}
@helper CommentText(NewsfeedPost post)
    {
    var commentText = string.Empty;
    if (post.TotalComments != null && post.TotalComments > 0)
    {
        commentText = post.TotalComments == 1 ?
            string.Format("1 {0}", Model.Content[NewsFeedContent.Comment]) :
            string.Format("{0} {1}", post.TotalComments, Model.Content[NewsFeedContent.Comments]);
    }
    if (!string.IsNullOrEmpty(commentText))
    {
        <img class="likeImage" src="/images/social/icon-comments.gif" alt="comments" style="width: 16px; height:16px; border:0;" />
    }
    <span class="newsfeedSubText grey">@commentText</span>
}   

<div class="newsfeedContainer">
    <textarea style="width:240px;overflow: auto;" class="box grey disabled" rows="2" cols="45" id="newPostText" hasText="false" message="@Model.NewsfeedMessage">@Model.NewsfeedMessage</textarea>
    <input id="submitPost" type="button" class="disabled" value="@Model.Content[NewsFeedContent.Post]"/> 
    <ul id="newsfeedList">
        @if (Model.NewsFeed.Count == 0)
        {
            <li id="nothingPosted" class="newsFeedItem">
                <h3 class="grey" style="width:260px">@Model.Content[NewsFeedContent.NothingPosted]</h3>
                <div>
                    <span class="newsfeedSubText grey postDate"></span>
                </div>  
            </li>
        }
        @foreach (var post in Model.NewsFeed)
        {
        <li class="newsFeedItem">
            @PostImage(post) 
            <h4 class="grey postText">@PostText(post)</h4>
            <div>
                <span class="newsfeedSubText grey">@post.PostDate.ToString(Model.CurrentCulture)</span> 
                <a href="#" class="tertiary likeLink LikeClassic" postbyid="@post.PostById" youlikedid="@post.YouLikedId" groupid="@post.GroupId" postid="@post.PostId" youlikedit="@post.YouLikeThis.ToString()">@(post.YouLikeThis ? @Model.Content[NewsFeedContent.Unlike] : @Model.Content[NewsFeedContent.Like])</a>
                <a href="/Secure/Social/MyNewsFeed.aspx?nfid=Wall_@post.PostId" class="tertiary LikeClassic">@Model.Content[NewsFeedContent.Comment]</a>                
            </div>             
                <div>@LikeText(post)</div>
                <div>@CommentText(post)</div>            
        </li>
        }
        <li id="newsFeedItemTemplate">
            <img alt="" src="@Model.MemberImage" />
            <h4 class="grey postText"></h4>
            <div>
                <span class="newsfeedSubText grey postDate"></span>
            </div> 
        </li>
    </ul>
</div>
<div id="divRemoveFriend" style="display:none;">
    <div>@Model.Content[NewsFeedContent.SureRemoveAsFriend]</div>
    <br /><br />
    <div style="text-align:right;">
        <input type="button" value="@Model.Content[NewsFeedContent.Cancel]" onclick="$('#divRemoveFriend').dialog('close');" class="vbtn_gray_a_md" id="btnCancel" name="btnCancel" style="padding:0px 10px 5px 10px;" />
        <input type="button" value="Model.Content[NewsFeedContent.Yes]" class="vbtn_red_a_md" id="btnRemove" name="btnRemove" style="padding:0px 10px 5px 10px;"/>
    </div>
</div>
         